# Generated by Django 5.0.1 on 2024-01-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employe',
            name='fullnamer',
        ),
        migrations.RemoveField(
            model_name='employe',
            name='moblie',
        ),
        migrations.AddField(
            model_name='employe',
            name='fullname',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='employe',
            name='mobile',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
